### PR TITLE
Usability improvements

### PR DESCRIPTION
**Pull request by domportera**
1. Option to choose to use all barcodes or just QR codes
2. Option to hasten minutes UI speed
3. Option to allow for alarm dismissal without scanning before the alarm goes off

edit:
4. Display time until alarm time shown

### CODE REVIEW

**Comment by sweakpl** [comment]
Hey, thank you for your work! I will look into it as soon as I have my other things sorted out 😅

**Comment by domportera** [comment]
no worries, take your time! thank you for your work on making the app in the first place :)

one thing i should note is that the fast movement for the minutes messes with the animations for some reason, wasnt able to figure that one out in the time i spent 🤷‍♂️

**Comment by sweakpl** [comment]
Hey, I've decided to build upon your commit with the support for barcodes. Thanks for contribution! :D

When it comes to the no-code alarm dismissal before alarm goes off, I've decided not to implement that functionality (more [here](https://github.com/sweakpl/qralarm-android/issues/15))

The rest of the ideas might possibly be added in the future, but for now I'm closing this PR.

**Comment by domportera** [comment]
no problem! glad i can be of some help :)

**Pull request closed without merging**
